seed: 42
project: local2global-nmr
train: true
test: false

data_path: ${oc.env:DATA_PATH}
data_name: uspto

group: step-2-nmr2graph-edge
# exp_name: dim512-nonebondw0.4-graphjoinencoder-finetunefromepoch38-bs64
# exp_name: dim256-finetunefromepoch42
# exp_name: joint-bixt-graph-d512-nonebondw0.8-smiw1.0-neighborw1.0-Cvalw0.25frag-run1
exp_name: joint-graph-d512-nonebondw0.8-smiw1.0-neighborw1.0-Cvalw0.25frag

exp_save_dir_name: ${group}/${exp_name}_${now:%Y-%m-%d}_${now:%H-%M-%S}
output_dir: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/Unsupervised_NMR/exp/local2global/${data_name}/${exp_save_dir_name}
log_path: ${output_dir}/logs


load_weights_strict: false

# only_load_weights: true
# ckpt_path: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/Unsupervised_NMR/exp/local2global/uspto/step-1-nmr2graph/refined_atom_nmr-neighborcountloss0.1-fragment_smiles-d512-run1_2026-07-23_12-14-26/checkpoints/epoch=038.ckpt

# only_load_weights: true
# ckpt_path: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/Unsupervised_NMR/exp/local2global/uspto/step-2-nmr2graph-edge/dim512-finetunefromepoch38_bs64_2026-07-26_00-17-30/checkpoints/last.ckpt

# only_load_weights: true
# ckpt_path: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/Unsupervised_NMR/exp/local2global/uspto/step-1-nmr2fragment/joint-bixt-fragment-Cvalw0.1-d512_2026-08-23_14-58-04/checkpoints/epoch=033.ckpt

# only_load_weights: false
# ckpt_path: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/Unsupervised_NMR/exp/local2global/uspto/step-2-nmr2graph-edge/joint-bixt-graph-d512-nonebondw0.8-smiw1.0-neighborw1.0-Cvalw0.25frag_2026-08-25_23-31-34/checkpoints/last.ckpt

only_load_weights: true
ckpt_path: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/Unsupervised_NMR/exp/local2global/uspto/step-1-nmr2fragment/joint-fragment-Cvalw0.1-d512_2026-09-02_12-38-22/checkpoints/epoch=036.ckpt

hidden_dim: 512
num_heads: 8
max_num_atoms: 101
val_check_interval: 0.5
inference_only_validation: true

datamodule:
  _target_: src.data.datamodule.NMRGraphDataModule
  train_path: ${data_path}/train.pt
  val_path: ${data_path}/val.pt
  test_path: ${data_path}/test.pt
  train_batch_size: 64
  val_batch_size: 32
  num_workers: 1
  pin_memory: true
  val_generation_size: 1024
  val_generation_seed: 0
  inference_only_validation: ${inference_only_validation}
  batch_transform:
    _target_: src.data.transforms.NormalizeNMR
    stats_path: ${data_path}/dataset_infos_train.json
    normalize_h_shift: true
    normalize_c_shift: true
    normalize_h_integration: true
    normalize_h_j: true
    encode_multiplicity: false
    encode_smiles: false
    max_multiplicity_classes: 122

lit_module:
  _target_: src.lit.module.LitNMRToGraph
  model:
    _target_: src.model.nmr_to_graph.NMRToGraph
    hidden_dim: ${hidden_dim}
    num_heads: ${num_heads}
    num_joint_layers: 6
    num_atom_interaction_layers: 2
    num_fourier_features: 64
    max_num_atoms: ${max_num_atoms}
    num_bond_types: 5
    max_fragment_count: 4
    attachment_dim: 128
    attachment_temperature: 0.1
    use_h_integration: true
    use_h_multiplicity: true
    use_h_j: true
    max_multiplicity_classes: 122
    use_smiles_loss: true
    use_smiles_conditioning: false
    use_smiles_joint_bixt: false
    smiles_memory: joint
    num_smiles_layers: 5
    max_smiles_length: 75
    smiles_vocab_path: ${data_path}/dataset_infos_train.json
    teacher_force_smiles_during_eval: false
    predict_attachments: true
    predict_edges: true
    use_graph_joint_encoder: true
    num_graph_joint_layers: 1
    dropout: 0.1
  criterion:
    _target_: src.model.loss.NMRGraphLoss
    heavy_fragment_weight: 1.0
    heavy_fragment_presence_weight: 0.25
    heavy_neighbor_count_weight: 0.1
    fragment_carbon_valence_weight: 0.1
    max_heavy_neighbor_counts:
      6: 4
      7: 4
      8: 2
      9: 1
      15: 4
      16: 4
      17: 1
      35: 1
      53: 1
    h_parent_fragment_weight: 1.0
    h_parent_presence_weight: 0.25
    h_parent_type_weight: 0.25
    h_attachment_weight: 1.0
    h_count_weight: 0.25
    h_entropy_weight: 0.0
    edge_weight: 1.0
    edge_none_class_weight: 0.8
    edge_bond_class_weight: 1.0
    edge_total_neighbor_count_weight: 1.0
    carbon_valence_weight: 0.25
    fragment_edge_consistency_weight: 0.25
    smiles_weight: 1.0
    permutation_invariant_hydrogens: true
  lr: 2e-4
  weight_decay: 1e-12
  warm_up_steps: 100
  num_val_examples_to_log: 10
  inference_only_validation: ${inference_only_validation}
  validation_stage: graph

callbacks:
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: ${output_dir}/checkpoints
    filename: "{epoch:03d}-{step}"
    monitor: val_inference/graph_score
    mode: max
    save_last: true
    save_top_k: 3
  learning_rate_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step

logger:
  wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    save_dir: ${output_dir}
    project: ${project}
    log_model: false
    name: ${exp_name}

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: auto
  devices: 1
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
  max_epochs: 100
  num_sanity_val_steps: 2
  val_check_interval: ${val_check_interval}
  # check_val_every_n_epoch: 1


optimized_metric: val_inference/graph_score

hydra:
  run:
    dir: ${log_path}
